spring:
  profiles:
    active: test
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:FoodyLab-for-test;MODE=MYSQL;
    username: sa
    password:
  flyway:
    enabled: true
    encoding: UTF-8
    user: sa
    password: