server:
  port: 8080

spring:
  profiles:
    active: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:FoodyLab-for-test;MODE=MYSQL;
    username: sa
    password:
  flyway:
    enabled: true
    encoding: UTF-8
    user: sa
    password: