server:
  port: 8080

mybatis:
  type-aliases-package: app.foodylab
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/sample?characterEncoding=utf8
    username: sample_user
    password: 123456
